export const BAD_CREDENTIALS = 'BAD_CREDENTIALS';
export const NO_DATA = 'NO_DATA';


export const LS_STORAGE_PREFIX = '$-ATAMEKEN_ACADEMY_LOCAL_STORAGE-';

export const LS_USERS = LS_STORAGE_PREFIX + 'USERS';